### PR TITLE
Implement SonarCloud scanner

### PR DESCRIPTION
**Pull request by okhan-okbay-cko**
Scan the codebase with SonarCloud.
Analysis report can be found at: https://sonarcloud.io/summary/overall?id=checkout_checkout-3ds-sdk-ios

### CODE REVIEW

**Comment by okhan-okbay-cko** [comment]
This is failing. Will have a second look soon

**Comment by okhan-okbay-cko** [comment]
Might worth squashing two commits into one `Integrate Sonar Cloud Scanner via GitHub Actions` or something like that to reflect the context with the right changes. Since the first commit has the wrong and old implementation, it won't help the future readers of the git history 🙏  @aashna-narula-cko

**Comment by okhan-okbay-cko** [comment]
Might worth squashing two commits into one Integrate Sonar Cloud Scanner via GitHub Actions or something like that to reflect the context with the right changes. Since the first commit has the wrong and old implementation, it won't help the future readers of the git history 🙏 @aashna-narula-cko

**Review by okhan-okbay-cko — COMMENTED** [review]
Might worth squashing two commits into one Integrate Sonar Cloud Scanner via GitHub Actions or something like that to reflect the context with the right changes. Since the first commit has the wrong and old implementation, it won't help the future readers of the git history 🙏 @aashna-narula-cko

**Review by aashna-narula-cko — APPROVED** [review]

**Pull request merged**
